/********************************************************************
* ModuleDatDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ModuleDatDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableModuleDatDict();
extern void G__cpp_setup_inheritanceModuleDatDict();
extern void G__cpp_setup_typetableModuleDatDict();
extern void G__cpp_setup_memvarModuleDatDict();
extern void G__cpp_setup_globalModuleDatDict();
extern void G__cpp_setup_memfuncModuleDatDict();
extern void G__cpp_setup_funcModuleDatDict();
extern void G__set_cpp_environmentModuleDatDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/ModuleDat.h"
#include "include/ModuleCal.h"
#include "include/CoincEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ModuleDatDictLN_TClass;
extern G__linked_taginfo G__ModuleDatDictLN_TBuffer;
extern G__linked_taginfo G__ModuleDatDictLN_TMemberInspector;
extern G__linked_taginfo G__ModuleDatDictLN_TObject;
extern G__linked_taginfo G__ModuleDatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ModuleDatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ModuleDatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ModuleDatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ModuleDatDictLN_ModuleDat;
extern G__linked_taginfo G__ModuleDatDictLN_ModuleCal;
extern G__linked_taginfo G__ModuleDatDictLN_CoincEvent;

/* STUB derived class for protected member access */
