//
// File generated by rootcint at Tue Oct  8 15:17:02 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ModuleDatDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ModuleDatDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ModuleDat_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ModuleDat(void *p = 0);
   static void *newArray_ModuleDat(Long_t size, void *p);
   static void delete_ModuleDat(void *p);
   static void deleteArray_ModuleDat(void *p);
   static void destruct_ModuleDat(void *p);
   static void streamer_ModuleDat(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ModuleDat*)
   {
      ::ModuleDat *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ModuleDat >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ModuleDat", ::ModuleDat::Class_Version(), "./include/ModuleDat.h", 8,
                  typeid(::ModuleDat), DefineBehavior(ptr, ptr),
                  &::ModuleDat::Dictionary, isa_proxy, 0,
                  sizeof(::ModuleDat) );
      instance.SetNew(&new_ModuleDat);
      instance.SetNewArray(&newArray_ModuleDat);
      instance.SetDelete(&delete_ModuleDat);
      instance.SetDeleteArray(&deleteArray_ModuleDat);
      instance.SetDestructor(&destruct_ModuleDat);
      instance.SetStreamerFunc(&streamer_ModuleDat);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ModuleDat*)
   {
      return GenerateInitInstanceLocal((::ModuleDat*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ModuleDat*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void ModuleCal_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ModuleCal(void *p = 0);
   static void *newArray_ModuleCal(Long_t size, void *p);
   static void delete_ModuleCal(void *p);
   static void deleteArray_ModuleCal(void *p);
   static void destruct_ModuleCal(void *p);
   static void streamer_ModuleCal(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ModuleCal*)
   {
      ::ModuleCal *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ModuleCal >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ModuleCal", ::ModuleCal::Class_Version(), "./include/ModuleCal.h", 8,
                  typeid(::ModuleCal), DefineBehavior(ptr, ptr),
                  &::ModuleCal::Dictionary, isa_proxy, 0,
                  sizeof(::ModuleCal) );
      instance.SetNew(&new_ModuleCal);
      instance.SetNewArray(&newArray_ModuleCal);
      instance.SetDelete(&delete_ModuleCal);
      instance.SetDeleteArray(&deleteArray_ModuleCal);
      instance.SetDestructor(&destruct_ModuleCal);
      instance.SetStreamerFunc(&streamer_ModuleCal);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ModuleCal*)
   {
      return GenerateInitInstanceLocal((::ModuleCal*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ModuleCal*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void CoincEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_CoincEvent(void *p = 0);
   static void *newArray_CoincEvent(Long_t size, void *p);
   static void delete_CoincEvent(void *p);
   static void deleteArray_CoincEvent(void *p);
   static void destruct_CoincEvent(void *p);
   static void streamer_CoincEvent(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CoincEvent*)
   {
      ::CoincEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CoincEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CoincEvent", ::CoincEvent::Class_Version(), "./include/CoincEvent.h", 10,
                  typeid(::CoincEvent), DefineBehavior(ptr, ptr),
                  &::CoincEvent::Dictionary, isa_proxy, 0,
                  sizeof(::CoincEvent) );
      instance.SetNew(&new_CoincEvent);
      instance.SetNewArray(&newArray_CoincEvent);
      instance.SetDelete(&delete_CoincEvent);
      instance.SetDeleteArray(&deleteArray_CoincEvent);
      instance.SetDestructor(&destruct_CoincEvent);
      instance.SetStreamerFunc(&streamer_CoincEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CoincEvent*)
   {
      return GenerateInitInstanceLocal((::CoincEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CoincEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *ModuleDat::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *ModuleDat::Class_Name()
{
   return "ModuleDat";
}

//______________________________________________________________________________
const char *ModuleDat::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ModuleDat*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ModuleDat::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ModuleDat*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ModuleDat::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ModuleDat*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ModuleDat::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ModuleDat*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *ModuleCal::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *ModuleCal::Class_Name()
{
   return "ModuleCal";
}

//______________________________________________________________________________
const char *ModuleCal::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ModuleCal*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ModuleCal::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ModuleCal*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ModuleCal::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ModuleCal*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ModuleCal::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ModuleCal*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *CoincEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CoincEvent::Class_Name()
{
   return "CoincEvent";
}

//______________________________________________________________________________
const char *CoincEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CoincEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CoincEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CoincEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CoincEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CoincEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CoincEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CoincEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void ModuleDat::Streamer(TBuffer &R__b)
{
   // Stream an object of class ModuleDat.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> ct;
      R__b >> chip;
      R__b >> module;
      R__b >> apd;
      R__b >> Ec;
      R__b >> Ech;
      R__b >> x;
      R__b >> y;
      R__b >> E;
      R__b >> ft;
      R__b >> pos;
      R__b >> a;
      R__b >> b;
      R__b >> c;
      R__b >> d;
      R__b >> id;
      R__b.CheckByteCount(R__s, R__c, ModuleDat::IsA());
   } else {
      R__c = R__b.WriteVersion(ModuleDat::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << ct;
      R__b << chip;
      R__b << module;
      R__b << apd;
      R__b << Ec;
      R__b << Ech;
      R__b << x;
      R__b << y;
      R__b << E;
      R__b << ft;
      R__b << pos;
      R__b << a;
      R__b << b;
      R__b << c;
      R__b << d;
      R__b << id;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void ModuleDat::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ModuleDat.
      TClass *R__cl = ::ModuleDat::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ct", &ct);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chip", &chip);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "module", &module);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "apd", &apd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ec", &Ec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ech", &Ech);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x", &x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y", &y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E", &E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ft", &ft);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pos", &pos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "a", &a);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "b", &b);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "c", &c);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d", &d);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "id", &id);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ModuleDat(void *p) {
      return  p ? new(p) ::ModuleDat : new ::ModuleDat;
   }
   static void *newArray_ModuleDat(Long_t nElements, void *p) {
      return p ? new(p) ::ModuleDat[nElements] : new ::ModuleDat[nElements];
   }
   // Wrapper around operator delete
   static void delete_ModuleDat(void *p) {
      delete ((::ModuleDat*)p);
   }
   static void deleteArray_ModuleDat(void *p) {
      delete [] ((::ModuleDat*)p);
   }
   static void destruct_ModuleDat(void *p) {
      typedef ::ModuleDat current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_ModuleDat(TBuffer &buf, void *obj) {
      ((::ModuleDat*)obj)->::ModuleDat::Streamer(buf);
   }
} // end of namespace ROOT for class ::ModuleDat

//______________________________________________________________________________
void ModuleCal::Streamer(TBuffer &R__b)
{
   // Stream an object of class ModuleCal.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> ct;
      R__b >> ft;
      R__b >> Ecal;
      R__b >> E;
      R__b >> Ec;
      R__b >> Ech;
      R__b >> x;
      R__b >> y;
      R__b >> chip;
      R__b >> fin;
      R__b >> m;
      R__b >> apd;
      R__b >> id;
      R__b >> pos;
      R__b.CheckByteCount(R__s, R__c, ModuleCal::IsA());
   } else {
      R__c = R__b.WriteVersion(ModuleCal::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << ct;
      R__b << ft;
      R__b << Ecal;
      R__b << E;
      R__b << Ec;
      R__b << Ech;
      R__b << x;
      R__b << y;
      R__b << chip;
      R__b << fin;
      R__b << m;
      R__b << apd;
      R__b << id;
      R__b << pos;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void ModuleCal::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ModuleCal.
      TClass *R__cl = ::ModuleCal::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ct", &ct);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ft", &ft);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ecal", &Ecal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E", &E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ec", &Ec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ech", &Ech);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x", &x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y", &y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chip", &chip);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fin", &fin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m", &m);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "apd", &apd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "id", &id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pos", &pos);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ModuleCal(void *p) {
      return  p ? new(p) ::ModuleCal : new ::ModuleCal;
   }
   static void *newArray_ModuleCal(Long_t nElements, void *p) {
      return p ? new(p) ::ModuleCal[nElements] : new ::ModuleCal[nElements];
   }
   // Wrapper around operator delete
   static void delete_ModuleCal(void *p) {
      delete ((::ModuleCal*)p);
   }
   static void deleteArray_ModuleCal(void *p) {
      delete [] ((::ModuleCal*)p);
   }
   static void destruct_ModuleCal(void *p) {
      typedef ::ModuleCal current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_ModuleCal(TBuffer &buf, void *obj) {
      ((::ModuleCal*)obj)->::ModuleCal::Streamer(buf);
   }
} // end of namespace ROOT for class ::ModuleCal

//______________________________________________________________________________
void CoincEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class CoincEvent.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> dtc;
      R__b >> dtf;
      R__b >> E1;
      R__b >> Ec1;
      R__b >> Ech1;
      R__b >> ft1;
      R__b >> E2;
      R__b >> Ec2;
      R__b >> Ech2;
      R__b >> ft2;
      R__b >> x1;
      R__b >> y1;
      R__b >> x2;
      R__b >> y2;
      R__b >> chip1;
      R__b >> fin1;
      R__b >> m1;
      R__b >> apd1;
      R__b >> crystal1;
      R__b >> chip2;
      R__b >> fin2;
      R__b >> m2;
      R__b >> apd2;
      R__b >> crystal2;
      R__b >> pos;
      R__b.CheckByteCount(R__s, R__c, CoincEvent::IsA());
   } else {
      R__c = R__b.WriteVersion(CoincEvent::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << dtc;
      R__b << dtf;
      R__b << E1;
      R__b << Ec1;
      R__b << Ech1;
      R__b << ft1;
      R__b << E2;
      R__b << Ec2;
      R__b << Ech2;
      R__b << ft2;
      R__b << x1;
      R__b << y1;
      R__b << x2;
      R__b << y2;
      R__b << chip1;
      R__b << fin1;
      R__b << m1;
      R__b << apd1;
      R__b << crystal1;
      R__b << chip2;
      R__b << fin2;
      R__b << m2;
      R__b << apd2;
      R__b << crystal2;
      R__b << pos;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void CoincEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class CoincEvent.
      TClass *R__cl = ::CoincEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtc", &dtc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtf", &dtf);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E1", &E1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ec1", &Ec1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ech1", &Ech1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ft1", &ft1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E2", &E2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ec2", &Ec2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ech2", &Ech2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ft2", &ft2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x1", &x1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y1", &y1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x2", &x2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y2", &y2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chip1", &chip1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fin1", &fin1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m1", &m1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "apd1", &apd1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "crystal1", &crystal1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chip2", &chip2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fin2", &fin2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m2", &m2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "apd2", &apd2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "crystal2", &crystal2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pos", &pos);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_CoincEvent(void *p) {
      return  p ? new(p) ::CoincEvent : new ::CoincEvent;
   }
   static void *newArray_CoincEvent(Long_t nElements, void *p) {
      return p ? new(p) ::CoincEvent[nElements] : new ::CoincEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_CoincEvent(void *p) {
      delete ((::CoincEvent*)p);
   }
   static void deleteArray_CoincEvent(void *p) {
      delete [] ((::CoincEvent*)p);
   }
   static void destruct_CoincEvent(void *p) {
      typedef ::CoincEvent current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_CoincEvent(TBuffer &buf, void *obj) {
      ((::CoincEvent*)obj)->::CoincEvent::Streamer(buf);
   }
} // end of namespace ROOT for class ::CoincEvent

/********************************************************
* ModuleDatDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableModuleDatDict();

extern "C" void G__set_cpp_environmentModuleDatDict() {
  G__cpp_reset_tagtableModuleDatDict();
}
#include <new>
extern "C" int G__cpp_dllrevModuleDatDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ModuleDat */
static int G__ModuleDatDict_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ModuleDat* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ModuleDat[n];
     } else {
       p = new((void*) gvp) ModuleDat[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ModuleDat;
     } else {
       p = new((void*) gvp) ModuleDat;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleDat));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ModuleDat::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ModuleDat::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ModuleDat::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ModuleDat::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_168_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ModuleDat*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ModuleDat::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ModuleDat::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ModuleDat::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ModuleDat::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ModuleDatDict_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ModuleDat* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ModuleDat(*(ModuleDat*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleDat));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ModuleDat G__TModuleDat;
static int G__ModuleDatDict_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ModuleDat*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ModuleDat*) (soff+(sizeof(ModuleDat)*i)))->~G__TModuleDat();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ModuleDat*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ModuleDat*) (soff))->~G__TModuleDat();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ModuleDatDict_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ModuleDat* dest = (ModuleDat*) G__getstructoffset();
   *dest = *(ModuleDat*) libp->para[0].ref;
   const ModuleDat& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* ModuleCal */
static int G__ModuleDatDict_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ModuleCal* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ModuleCal[n];
     } else {
       p = new((void*) gvp) ModuleCal[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ModuleCal;
     } else {
       p = new((void*) gvp) ModuleCal;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleCal));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ModuleCal::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ModuleCal::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ModuleCal::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ModuleCal::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ModuleCal*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_169_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ModuleCal::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_169_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ModuleCal::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_169_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ModuleCal::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_169_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ModuleCal::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ModuleDatDict_169_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ModuleCal* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ModuleCal(*(ModuleCal*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleCal));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ModuleCal G__TModuleCal;
static int G__ModuleDatDict_169_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ModuleCal*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ModuleCal*) (soff+(sizeof(ModuleCal)*i)))->~G__TModuleCal();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ModuleCal*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ModuleCal*) (soff))->~G__TModuleCal();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ModuleDatDict_169_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ModuleCal* dest = (ModuleCal*) G__getstructoffset();
   *dest = *(ModuleCal*) libp->para[0].ref;
   const ModuleCal& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* CoincEvent */
static int G__ModuleDatDict_170_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CoincEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CoincEvent[n];
     } else {
       p = new((void*) gvp) CoincEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CoincEvent;
     } else {
       p = new((void*) gvp) CoincEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ModuleDatDictLN_CoincEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_170_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CoincEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_170_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CoincEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_170_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CoincEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_170_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CoincEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_170_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CoincEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_170_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CoincEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_170_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CoincEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_170_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CoincEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ModuleDatDict_170_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CoincEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ModuleDatDict_170_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CoincEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CoincEvent(*(CoincEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ModuleDatDictLN_CoincEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CoincEvent G__TCoincEvent;
static int G__ModuleDatDict_170_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CoincEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CoincEvent*) (soff+(sizeof(CoincEvent)*i)))->~G__TCoincEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CoincEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CoincEvent*) (soff))->~G__TCoincEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ModuleDatDict_170_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CoincEvent* dest = (CoincEvent*) G__getstructoffset();
   *dest = *(CoincEvent*) libp->para[0].ref;
   const CoincEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ModuleDat */

/* ModuleCal */

/* CoincEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncModuleDatDict {
 public:
  G__Sizep2memfuncModuleDatDict(): p(&G__Sizep2memfuncModuleDatDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncModuleDatDict::*p)();
};

size_t G__get_sizep2memfuncModuleDatDict()
{
  G__Sizep2memfuncModuleDatDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceModuleDatDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleDat))) {
     ModuleDat *G__Lderived;
     G__Lderived=(ModuleDat*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleDat),G__get_linked_tagnum(&G__ModuleDatDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleCal))) {
     ModuleCal *G__Lderived;
     G__Lderived=(ModuleCal*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleCal),G__get_linked_tagnum(&G__ModuleDatDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ModuleDatDictLN_CoincEvent))) {
     CoincEvent *G__Lderived;
     G__Lderived=(CoincEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ModuleDatDictLN_CoincEvent),G__get_linked_tagnum(&G__ModuleDatDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableModuleDatDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ModuleDatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ModuleDatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ModuleDatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ModuleDatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ModuleDatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ModuleDatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ModuleDatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ModuleDatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ModuleDatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ModuleDatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ModuleDat */
static void G__setup_memvarModuleDat(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleDat));
   { ModuleDat *p; p=(ModuleDat*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->ct)-(long)(p)),110,0,0,-1,G__defined_typename("Long64_t"),-1,1,"ct=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chip)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"chip=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->module)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"module=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->apd)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"apd=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ec)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ech)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ech=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->E)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"E=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ft)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"ft=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pos)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"pos=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->a)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"a=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"b=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->c)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"c=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->d)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"d=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->id)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"id=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ModuleDatDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* ModuleCal */
static void G__setup_memvarModuleCal(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleCal));
   { ModuleCal *p; p=(ModuleCal*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->ct)-(long)(p)),110,0,0,-1,G__defined_typename("Long64_t"),-1,1,"ct=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ft)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"ft=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ecal)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ecal=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->E)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"E=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ec)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ech)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ech=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chip)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"chip=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fin)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"fin=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"m=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->apd)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"apd=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->id)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"id=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pos)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"pos=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ModuleDatDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* CoincEvent */
static void G__setup_memvarCoincEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ModuleDatDictLN_CoincEvent));
   { CoincEvent *p; p=(CoincEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->dtc)-(long)(p)),110,0,0,-1,G__defined_typename("Long64_t"),-1,1,"dtc=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtf)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dtf=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->E1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"E1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ec1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ec1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ech1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ech1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ft1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ft1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->E2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"E2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ec2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ec2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ech2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Ech2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ft2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ft2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->x1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"x1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"y1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->x2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"x2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"y2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chip1)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"chip1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fin1)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"fin1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m1)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"m1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->apd1)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"apd1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->crystal1)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"crystal1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chip2)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"chip2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fin2)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"fin2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->m2)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"m2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->apd2)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"apd2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->crystal2)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"crystal2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pos)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"pos=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ModuleDatDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarModuleDatDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncModuleDat(void) {
   /* ModuleDat */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleDat));
   G__memfunc_setup("ModuleDat",895,G__ModuleDatDict_168_0_1, 105, G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleDat), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ModuleDatDict_168_0_2, 85, G__get_linked_tagnum(&G__ModuleDatDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ModuleDat::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ModuleDatDict_168_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ModuleDat::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ModuleDatDict_168_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ModuleDat::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ModuleDatDict_168_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ModuleDat::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ModuleDatDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ModuleDatDict_168_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ModuleDatDict_168_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ModuleDat::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ModuleDatDict_168_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ModuleDat::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ModuleDatDict_168_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ModuleDat::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ModuleDatDict_168_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ModuleDat::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("ModuleDat", 895, G__ModuleDatDict_168_0_14, (int) ('i'), G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleDat), -1, 0, 1, 1, 1, 0, "u 'ModuleDat' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ModuleDat", 1021, G__ModuleDatDict_168_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ModuleDatDict_168_0_16, (int) ('u'), G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleDat), -1, 1, 1, 1, 1, 0, "u 'ModuleDat' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncModuleCal(void) {
   /* ModuleCal */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleCal));
   G__memfunc_setup("ModuleCal",886,G__ModuleDatDict_169_0_1, 105, G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleCal), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ModuleDatDict_169_0_2, 85, G__get_linked_tagnum(&G__ModuleDatDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ModuleCal::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ModuleDatDict_169_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ModuleCal::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ModuleDatDict_169_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ModuleCal::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ModuleDatDict_169_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ModuleCal::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ModuleDatDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ModuleDatDict_169_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ModuleDatDict_169_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ModuleCal::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ModuleDatDict_169_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ModuleCal::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ModuleDatDict_169_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ModuleCal::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ModuleDatDict_169_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ModuleCal::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("ModuleCal", 886, G__ModuleDatDict_169_0_14, (int) ('i'), G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleCal), -1, 0, 1, 1, 1, 0, "u 'ModuleCal' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ModuleCal", 1012, G__ModuleDatDict_169_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ModuleDatDict_169_0_16, (int) ('u'), G__get_linked_tagnum(&G__ModuleDatDictLN_ModuleCal), -1, 1, 1, 1, 1, 0, "u 'ModuleCal' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncCoincEvent(void) {
   /* CoincEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ModuleDatDictLN_CoincEvent));
   G__memfunc_setup("CoincEvent",1006,G__ModuleDatDict_170_0_1, 105, G__get_linked_tagnum(&G__ModuleDatDictLN_CoincEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ModuleDatDict_170_0_2, 85, G__get_linked_tagnum(&G__ModuleDatDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&CoincEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ModuleDatDict_170_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CoincEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ModuleDatDict_170_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&CoincEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ModuleDatDict_170_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&CoincEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ModuleDatDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ModuleDatDict_170_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ModuleDatDict_170_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CoincEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ModuleDatDict_170_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CoincEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ModuleDatDict_170_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CoincEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ModuleDatDict_170_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CoincEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("CoincEvent", 1006, G__ModuleDatDict_170_0_14, (int) ('i'), G__get_linked_tagnum(&G__ModuleDatDictLN_CoincEvent), -1, 0, 1, 1, 1, 0, "u 'CoincEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CoincEvent", 1132, G__ModuleDatDict_170_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ModuleDatDict_170_0_16, (int) ('u'), G__get_linked_tagnum(&G__ModuleDatDictLN_CoincEvent), -1, 1, 1, 1, 1, 0, "u 'CoincEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncModuleDatDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalModuleDatDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcModuleDatDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ModuleDatDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_ModuleDat = { "ModuleDat" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_ModuleCal = { "ModuleCal" , 99 , -1 };
G__linked_taginfo G__ModuleDatDictLN_CoincEvent = { "CoincEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableModuleDatDict() {
  G__ModuleDatDictLN_TClass.tagnum = -1 ;
  G__ModuleDatDictLN_TBuffer.tagnum = -1 ;
  G__ModuleDatDictLN_TMemberInspector.tagnum = -1 ;
  G__ModuleDatDictLN_TObject.tagnum = -1 ;
  G__ModuleDatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ModuleDatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ModuleDatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ModuleDatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ModuleDatDictLN_ModuleDat.tagnum = -1 ;
  G__ModuleDatDictLN_ModuleCal.tagnum = -1 ;
  G__ModuleDatDictLN_CoincEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableModuleDatDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_ModuleDat),sizeof(ModuleDat),-1,29952,(char*)NULL,G__setup_memvarModuleDat,G__setup_memfuncModuleDat);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_ModuleCal),sizeof(ModuleCal),-1,29952,(char*)NULL,G__setup_memvarModuleCal,G__setup_memfuncModuleCal);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ModuleDatDictLN_CoincEvent),sizeof(CoincEvent),-1,29952,(char*)NULL,G__setup_memvarCoincEvent,G__setup_memfuncCoincEvent);
}
extern "C" void G__cpp_setupModuleDatDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupModuleDatDict()");
  G__set_cpp_environmentModuleDatDict();
  G__cpp_setup_tagtableModuleDatDict();

  G__cpp_setup_inheritanceModuleDatDict();

  G__cpp_setup_typetableModuleDatDict();

  G__cpp_setup_memvarModuleDatDict();

  G__cpp_setup_memfuncModuleDatDict();
  G__cpp_setup_globalModuleDatDict();
  G__cpp_setup_funcModuleDatDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncModuleDatDict();
  return;
}
class G__cpp_setup_initModuleDatDict {
  public:
    G__cpp_setup_initModuleDatDict() { G__add_setup_func("ModuleDatDict",(G__incsetup)(&G__cpp_setupModuleDatDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initModuleDatDict() { G__remove_setup_func("ModuleDatDict"); }
};
G__cpp_setup_initModuleDatDict G__cpp_setup_initializerModuleDatDict;

